// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO
    products (
        product_image_file,
        name,
        price,
        stock,
        category_id
    )
VALUES ($1, $2, $3, $4, $5)
RETURNING
    id, product_image_file, name, price, stock, category_id, created_at, updated_at
`

type CreateProductParams struct {
	ProductImageFile string
	Name             string
	Price            int64
	Stock            int32
	CategoryID       pgtype.UUID
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ProductImageFile,
		arg.Name,
		arg.Price,
		arg.Stock,
		arg.CategoryID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProductImageFile,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :one
DELETE FROM products WHERE id = $1 RETURNING id, product_image_file, name, price, stock, category_id, created_at, updated_at
`

func (q *Queries) DeleteProduct(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, deleteProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProductImageFile,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductById = `-- name: GetProductById :one
SELECT id, product_image_file, name, price, stock, category_id, created_at, updated_at FROM products WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProductById(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductById, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProductImageFile,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, product_image_file, name, price, stock, category_id, created_at, updated_at FROM products ORDER BY created_at DESC
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ProductImageFile,
			&i.Name,
			&i.Price,
			&i.Stock,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET
    product_image_file = COALESCE($1, product_image_file),
    name = COALESCE($2, name),
    price = COALESCE($3, price),
    stock = COALESCE($4, stock),
    category_id = COALESCE($5, category_id)
WHERE
    id = $6
RETURNING
    id, product_image_file, name, price, stock, category_id, created_at, updated_at
`

type UpdateProductParams struct {
	ProductImageFile string
	Name             string
	Price            int64
	Stock            int32
	CategoryID       pgtype.UUID
	ID               pgtype.UUID
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ProductImageFile,
		arg.Name,
		arg.Price,
		arg.Stock,
		arg.CategoryID,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProductImageFile,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
