// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO
    products (
        product_image_file,
        name,
        price,
        stock,
        category_id
    )
VALUES ($1, $2, $3, $4, $5)
RETURNING
    id, product_image_file, name, price, stock, category_id, created_at, updated_at
`

type CreateProductParams struct {
	ProductImageFile string
	Name             string
	Price            int64
	Stock            int32
	CategoryID       pgtype.UUID
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ProductImageFile,
		arg.Name,
		arg.Price,
		arg.Stock,
		arg.CategoryID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProductImageFile,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :one
DELETE FROM products WHERE id = $1 RETURNING id, product_image_file, name, price, stock, category_id, created_at, updated_at
`

func (q *Queries) DeleteProduct(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, deleteProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProductImageFile,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductById = `-- name: GetProductById :one
SELECT id, product_image_file, name, price, stock, category_id, created_at, updated_at FROM products WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProductById(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductById, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProductImageFile,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByName = `-- name: GetProductByName :one
SELECT id, product_image_file, name, price, stock, category_id, created_at, updated_at FROM products WHERE name = $1 LIMIT 1
`

func (q *Queries) GetProductByName(ctx context.Context, name string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByName, name)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProductImageFile,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT 
    p.id, p.product_image_file, p.name, p.price, p.stock, p.category_id, p.created_at, p.updated_at, 
    c.name as category_name
FROM products p
LEFT JOIN categories c ON p.category_id = c.id
WHERE 
    ((COALESCE($1::text, '') = '') OR (p.name ILIKE '%' || $1::text || '%'))
    AND ($2::uuid IS NULL OR p.category_id = $2::uuid)
ORDER BY p.created_at DESC
`

type ListProductsParams struct {
	Search     string
	CategoryID pgtype.UUID
}

type ListProductsRow struct {
	ID               pgtype.UUID
	ProductImageFile string
	Name             string
	Price            int64
	Stock            int32
	CategoryID       pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	CategoryName     pgtype.Text
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Search, arg.CategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductImageFile,
			&i.Name,
			&i.Price,
			&i.Stock,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET
    product_image_file = COALESCE($1, product_image_file),
    name = COALESCE($2, name),
    price = COALESCE($3, price),
    stock = COALESCE($4, stock),
    category_id = COALESCE($5, category_id)
WHERE
    id = $6
RETURNING
    id, product_image_file, name, price, stock, category_id, created_at, updated_at
`

type UpdateProductParams struct {
	ProductImageFile string
	Name             string
	Price            int64
	Stock            int32
	CategoryID       pgtype.UUID
	ID               pgtype.UUID
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ProductImageFile,
		arg.Name,
		arg.Price,
		arg.Stock,
		arg.CategoryID,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProductImageFile,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
